#!/bin/sh
#
# SRG-335x Debian Buster customizations
#
# Copyright (c) LYD/AAEON, 2020
#
# Authors:
#  KunYi <kunyi.chen@gmail.com>
#
# SPDX-License-Identifier: MIT
#
HOSTNAME=SRG-3352C
echo "$HOSTNAME" > /etc/hostname
echo "127.0.1.1	$HOSTNAME" >> /etc/hosts

# change default PATH enviroment variable for user
# replace PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games" to
#		  PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
sed -i "s/PATH=\"\/usr\/local\/bin:\/usr\/bin:\/bin:\/usr\/local\/games:\/usr\/games\"/PATH=\"\/usr\/local\/sbin:\/usr\/local\/bin:\/usr\/sbin:\/usr\/bin:\/sbin:\/bin:\/usr\/games:\/usr\/local\/games\"/g" /etc/profile

# patch PIDFILE of fail2ban
if [ -e /lib/systemd/system/fail2ban.service ]; then
sed -i "s/PIDFile=\/var\/run\/fail2ban\/fail2ban.pid/PIDFile=\/run\/fail2ban\/fail2ban.pid/g" /lib/systemd/system/fail2ban.service
fi
# patch PIDFILE of auditd
if [ -e /lib/systemd/system/auditd.service ]; then
sed -i "s/PIDFile=\/var\/run\/auditd.pid/PIDFile=\/run\/auditd.pid/g" /lib/systemd/system/auditd.service
fi

# override origin issue/motd files
# then to remove files
cp -rf /opt/srg52/etc/issue/* /etc/
rm -rf /opt/srg52/etc/

# disable hostapd, default not enable
systemctl disable hostapd.service || true

MODULES=/etc/initramfs-tools/modules
if [ -e ${MODULES} ]; then
	if ! grep -q "^overlay" ${MODULES}; then
		echo overlay >> ${MODULES}
	fi
else
	echo overlay > ${MODULES}
	chmod 644 ${MODULES}
fi

# workaround, due to install permission incorrect
if [ -f /etc/NetworkManager/system-connections/Modem.nmconnection ]; then
  chmod 600 /etc/NetworkManager/system-connections/Modem.nmconnection
fi

if [ -f /etc/NetworkManager/system-connections/Eth0.nmconnection ]; then
  chmod 600 /etc/NetworkManager/system-connections/Eth0.nmconnection
fi

if [ -f /etc/NetworkManager/system-connections/Eth1.nmconnection ]; then
  chmod 600 /etc/NetworkManager/system-connections/Eth1.nmconnection
fi

if [ -f /lib/systemd/system/uartmode.service ]; then
	systemctl mask uartmode.service || true
fi
update-initramfs -u
