#!/bin/bash -e
#
# Copyright (c) 2016-2020 Robert Nelson <robertcnelson@gmail.com>
# Copyright (c) 2020 LYD/AAEON, kunyi <kunyi.chen@gmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

run_hciattach () {
	hciattach_bin=$(which hciattach)

	if [ -f ${hciattach_bin} ] ; then
		if [ -f /sys/class/leds/wl18xx_bt_en/brightness ] ; then
			# Resetting the Bluetooth enable pin
			echo ${bt_disable} > /sys/class/leds/wl18xx_bt_en/brightness || true
			sleep 2
			echo ${bt_enable} > /sys/class/leds/wl18xx_bt_en/brightness || true
			sleep 4
			${hciattach_bin} ${bt_port} ${bt_settings} || true
			sleep 4
			if [ -e /sys/class/bluetooth/hci0 ] ; then
				return 0
			fi
			return 2 # failed
		fi
	fi
}

board=$(cat /proc/device-tree/model | sed "s/ /_/g" | tr -d '\000')
case "${board}" in
AAEON_SRG-3352C_IoT_Gateway)
	bt_enable="1"
	bt_disable="0"
	bt_port="/dev/ttyS5"
	bt_settings="texas 300000 flow"
	run_hciattach
	;;
*)
	unset bt_enable
	unset bt_disable
	unset bt_port
	unset bt_settings
	;;
esac
