#!/bin/sh -e

if ! id | grep -q root; then
	echo "must be run as root"
	exit
fi

systemctl unmask uartmode.service
systemctl enable uartmode.service
systemctl start uartmode.service

sed -i s/^OVERLAYS=.*/OVERLAYS=\"srg52-extension-b.dtbo\"/g /etc/default/u-boot-script
update-u-boot-script

echo "need reboot for enabled expansion board mode B"
