#!/bin/sh
#
# SRG-335x Debian Buster
#
# Copyright (c) LYD/AAEON, 2020
#
# Authors:
#  KunYi <kunyi.chen@gmail.com>
#
# SPDX-License-Identifier: MIT
#

if [ -f /etc/securetty ] ; then
  echo ""  >> /etc/securetty
  echo "# for USB gadget serial console" >> /etc/securetty
  echo "ttyGS0" >> /etc/securetty
fi
