#!/bin/sh
#
# SRG-335x Debian Buster
#
# Copyright (c) LYD/AAEON, 2020
#
# Authors:
#  KunYi <kunyi.chen@gmail.com>
#
# SPDX-License-Identifier: MIT
#

HOSTNAME=SRG-3352C
echo "$HOSTNAME" > /etc/hostname
echo "127.0.1.1 $HOSTNAME" >> /etc/hosts

if [ -f /etc/securetty ] ; then
  echo ""  >> /etc/securetty
  echo "# for USB gadget serial console" >> /etc/securetty
  echo "ttyGS0" >> /etc/securetty
fi

# workaround, due to install permission incorrect
if [ -f /etc/NetworkManager/system-connections/Modem.nmconnection ]; then
  chmod 600 /etc/NetworkManager/system-connections/Modem.nmconnection
fi
