#!/bin/sh -e
#
# Boot script generator for U-Boot
#
# Copyright (c) LYD/AAEON, 2020
#
# Authors:
#   KunYi <kunyi.chen@gmail.com>
#
# SPDX-License-Identifier: MIT
#

#set -x
mount -o remount,rw /boot

if [ -f /etc/default/u-boot-script ]; then
	. /etc/default/u-boot-script
fi

BOOT_CMD=$(mktemp)

KERNEL_VERSION=$(linux-version list | linux-version sort --reverse | head -1)

KERNEL_FILE="vmlinuz"
BOOT="bootz"

echo "${SCRIPT_PREPEND}" >> ${BOOT_CMD}
# for saveenv, for factory init
echo "if env exists initenv; then" \
	"echo \"read env. varables from EMMC passed\";" \
     "else" \
	"echo \"will save env. variables into EMMC\";" \
	"setenv initenv true;" \
	"saveenv;"	\
     "fi" >> ${BOOT_CMD}
# KERNEL_ARGS definition in /etc/default/u-boot-script
echo "setenv bootpart 0:\${distro_bootpart} " >> ${BOOT_CMD}
echo "run finduuid" >> ${BOOT_CMD}
echo "setenv bootargs console=\${console} \${optargs} root=PARTUUID=\${uuid} rw rootfstype=\${mmcrootfstype}" >> ${BOOT_CMD}
echo "load \${devtype} \${devnum}:\${distro_bootpart} \${fdt_addr_r}" \
	 "/dtbs/\${fdtfile}" >> ${BOOT_CMD}
echo "load \${devtype} \${devnum}:\${distro_bootpart} \${kernel_addr_r}" \
	"/${KERNEL_FILE}-${KERNEL_VERSION}" >> ${BOOT_CMD}

case "${NO_INITRD}" in
yes|1)
	INITRD_ADDR="-"
	;;
*)
	echo "load \${devtype} \${devnum}:\${distro_bootpart}" \
		"\${ramdisk_addr_r} /initrd.img-${KERNEL_VERSION}" \
		>> ${BOOT_CMD}
	INITRD_ADDR="\${ramdisk_addr_r}:\${filesize}"
	;;
esac

if [ -n "${OVERLAYS}" ]; then
	echo "fdt addr \${fdt_addr_r}" >> ${BOOT_CMD}
	# grant 1 MB to combined device tree
	echo "fdt resize 0x100000" >> ${BOOT_CMD}
	echo "setexpr overlay_addr_r \${fdt_addr_r} + 0x100000" >> ${BOOT_CMD}
	for OVERLAY in ${OVERLAYS}; do
		if ! echo $OVERLAY | grep -q "^/"; then
			OVERLAY_PATH=/dtbs/overlay/
		fi
		echo "load \${devtype} \${devnum}:\${distro_bootpart}" \
			"\${overlay_addr_r} ${OVERLAY_PATH}${OVERLAY}" \
			>> ${BOOT_CMD}
		echo "fdt apply \${overlay_addr_r}" >> ${BOOT_CMD}
	done
fi

echo "${BOOT} \${kernel_addr_r} ${INITRD_ADDR} \${fdt_addr_r}" >> ${BOOT_CMD}

mkimage -T script -A invalid -C none -d ${BOOT_CMD} /boot/boot.scr > /dev/null

rm ${BOOT_CMD}
sync && sync
mount -o remount,ro /boot

exit 0
